### ISSUE TITLE
Unify dimen size resources

### ISSUE THREAD

**Issue by Apisov** [covidwatchorg/covidwatch-android-en#21]
## TODO
- [x] Check for duplicates in sizes and resources. 
- [ ] Use only one source for the same sizes when it used more than once in the app. 

## Resources
https://github.com/covid19risk/covidwatch-android-en/pull/20#discussion_r423839878

**Comment by Apisov** [comment]
There are `padding_normal` , `padding_content`, and `default_padding` dimens with the same value of `16dp`
- [ ] Let's use only `padding_normal`
