### ISSUE TITLE
Add fake ExposureInformation objects from the menu

### ISSUE THREAD

**Issue by Apisov** [covidwatchorg/covidwatch-android-en#28]
## TODO
- [ ] Add debug menu item
- [ ] Add a fake object of `ExposureInformation` into database
- [ ] Update `ExposureSummary` object saved in the preferences with added previously `ExposureInformation` object

## Resources
- Use `RandomObjects` in [FakeExposureNotification](https://github.com/covid19risk/covidwatch-android-en/blob/dc03bed257c640d71d40ddd0b64f95dc773c6be7/app/src/main/java/org/covidwatch/android/exposurenotification/FakeExposureNotification.kt) in order to generate fake objects.
  - [Example](https://github.com/covid19risk/covidwatch-android-en/blob/f388e3101df17ad31c6321fab4d54102b5931d71/app/src/main/java/org/covidwatch/android/data/exposureinformation/ExposureInformationRepository.kt)

-  Use `ExposureInformationRepository` to save fake objects

**Comment by crayne** [comment]
I tried to make a "real" implementation of "fun exposureInformation" in "ExposureInformationRepository", but it did not return structured data. So I must be missing something.  But I did see an example of using Room in the Android docs, and one of the files was this:

```
@Entity
data class User(
    @PrimaryKey val uid: Int,
    @ColumnInfo(name = "first_name") val firstName: String?,
    @ColumnInfo(name = "last_name") val lastName: String?
)
```
The equivalent of this file would be our CovidExposureInformation.kt, and I don't see any column name definition in there, so maybe that is part of the issue.
