### ISSUE TITLE
Keep list of countries visited last n days

### ISSUE THREAD

**Issue by Apisov** [covidwatchorg/covidwatch-android-en#45]
## Issue
In order to fetch data from EN server we need a list of the regions visited by the user.

## TODO
- [ ] Add the [ACTION_NETWORK_COUNTRY_CHANGED](https://developer.android.com/reference/kotlin/android/telephony/TelephonyManager#action_network_country_changed) broadcast to detect when users change country
- [ ] Save list of countries visited in the last `n` days
- [ ] Delete the countries that were visit more than `n` days before
- [ ] Update the list every `n` days

## Resources
`n`  should be equal to the number that PHAs require for relevant exposure period. By default it's `14` following EN requirements for exposure keys.
