### ISSUE TITLE
Calibration features

### ISSUE THREAD

**Issue by Apisov** [covidwatchorg/covidwatch-android-en#87]
### TODO

- [x] Add the same ZIP file with [[30,33],[33,36],[36,39],[39,42],[42,45],[45,48],[48,51],[51,54],[54,57],[57,60],[60,63],[63,66],[66,69],[69,72],[72,75],[75,78],[78,81],[81,84],[84,87],[87,90],[90,93],[93,96],[96,99]] attenuation thresholds programmatically. This means there will be multiple exposure infos for the same exposure(Notice that the exposure info in the [video ](https://covid-watch.slack.com/files/UV69GPJ8M/F015SV8CMND/rpreplay_final1592226041.mp4)contains the Attenuation Threshold row for each detected exposure).
- [x] Arizona branding design
- [x] Export exposures with the configuration used to detect them.
```
struct ExposureConfigurationWithExposures: Encodable {
  let exposureConfiguration: String
  let possibleExposures: [Exposure]
}
```
- [x] Exported exposures json name format `DeviceName_Date_TestCase.json`. `TestCase` is an input by a tester

- [x] Export ZIP file using a specific name: `"\(UIDevice.current.name)_\(ISO8601DateFormatter.string(from: Date(), timeZone: TimeZone.current, formatOptions: [.withInternetDateTime, .withFractionalSeconds]))"`
